### PR TITLE
Various upgrades

### LINKED ISSUE #7: Expose lemma and path in Proof
Can you expose `Proof`'s `path` and `lemma` properties?

This is really a requirement for the library to be usable since otherwise created proof can't be stored anywhere.

### PR DESCRIPTION
**Pull request by nazar-pc**
* 2021 edition
* upgrade of dependencies (especially yanked `ring` versions)
* `no_std` support
* fixed #7 

I can help with passive maintenance of the crate if necessary.

### CODE REVIEW

**Comment by sitano** [comment]
Great work @nazar-pc !

**Comment by nazar-pc** [comment]
Thanks for quick review! Can I expect new release on crates.io?

**Comment by nazar-pc** [comment]
Friendly ping, @sitano, can you push `0.4.0` to crates.io, please?

**Comment by sitano** [comment]
@nazar-pc https://crates.io/crates/merkle_light/0.4.0 done

**Pull request merged**
